import { ConfigService } from '@nestjs/config';
import { BatchDto } from '../dto/batch.dto';
export declare class BatchService {
    private configService;
    private s3Client;
    private textractClient;
    private openai;
    private bucketName;
    private ocrApiKey;
    private ocrUrl;
    private chatbaseApiUrl;
    private chatbaseBearerToken;
    private chatbaseFieldExtractionId;
    private chatbaseFostIdentificationId;
    private chatbaseDossierAnalysisId;
    private chatbaseDossierInterpretationId;
    private readonly MAX_RETRIES;
    private readonly INITIAL_RETRY_DELAY;
    private readonly TEXTRACT_POLLING_INTERVAL;
    constructor(configService: ConfigService);
    private retryWithBackoff;
    processBatch(batchDto: BatchDto): Promise<any>;
    private processFilesInParallel;
    private processFile;
    private extractTextWithOCR;
    private analyzeWithOpenAI;
    private generateSeparatePdfs;
    private analyzeWithTextract;
    private extractTextFromBlocks;
    private waitForTextractAnalysis;
    private extractFieldsWithChatbase;
    private processFostIdentification;
    private processDossierAnalysis;
    private generateFinalInterpretation;
    private generateChatbaseMessage;
    private callChatbase;
    private formatDuration;
    private formatDurationFromNumber;
    private generateBatchReport;
    private generateExecutionReport;
    private listPdfFiles;
}
